spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://localhost:{server.port}/login/oauth2/code/{registrationId}"
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

google:
  safe-browsing:
    client:
      client-id: shortlink
      client-version: 0.1
    endpoint: ${GOOGLE_SAFE_BROWSING_URL}
    api-key: ${GOOGLE_SAFE_BROWSING_API_KEY}
    timeout: 3000
    threat-types:
      - MALWARE
      - SOCIAL_ENGINEERING
      - UNWANTED_SOFTWARE
      - POTENTIALLY_HARMFUL_APPLICATION
    platform-types:
      - ANY_PLATFORM
    threat-entry-types:
      - URL